request from RAS
galasa-dev/framework pull request #158
Opened 2020-09-07 09:17 UTC by DianaSlepikaite

Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>

2020-09-07 12:18 UTC, hobbit1983 commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/TestClassesRas.java
> +			directoryService=directory;
Instead of iterating - if it's the last one that you need.  you can call get size on the collection and then index it directly.

2020-09-07 12:19 UTC, hobbit1983 commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/TestClassesRas.java
> +			e.printStackTrace();
if this exception is thrown we should respond to the get request with a status != 200

2020-09-08 20:24 UTC, hobbit1983 submitted a review, later dismissed

2020-09-09 07:06 UTC, Michael-Baylis requested changes
Minor changes.

2020-09-09 07:06 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/TestClassesRas.java
> +		} catch (ResultArchiveStoreException e) {
All you need to do is throw ServletException(with message, e);

2020-09-09 07:06 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/ras/directory/DirectoryRASDirectoryService.java
> +				}else break;
Why break,  just ignore and carry on

2020-09-09 07:06 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/ras/directory/DirectoryRASDirectoryService.java
> +			}else break;
same,  no need for a break;

2020-09-09 09:56 UTC, Michael-Baylis approved these changes

2020-09-09 09:57 UTC, merged