Backup cps fix file
galasa-dev/framework pull request #229
Opened 2021-01-27 17:27 UTC by matthewchivers

Fixes issue where file path required a parent directory.

Closes galasa-dev/projectmanagement#568

2021-01-28 11:01 UTC, Michael-Baylis requested changes

2021-01-28 11:01 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/BackupCPS.java
> +			logger.info("Overwriting existing file: " + path.toUri().toString());
as the exception shouldn't be thrown.

2021-01-28 11:01 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/BackupCPS.java
> +			logger.info("Overwriting existing file: " + path.toUri().toString());
you should specify create replace option on the createFile

2021-01-28 16:27 UTC, matthewchivers commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/BackupCPS.java
> +			logger.info("Overwriting existing file: " + path.toUri().toString());
The good news is that using those options means `Files.write()` is only ever needed once - no "initialisation" etc. is necessary - so I'm removing the method.

The removal of this method also brings other methods (and some instance variables) existence into question. So have just refactored the code a bit.

2021-01-29 11:57 UTC, Michael-Baylis approved these changes

2021-01-29 12:17 UTC, merged