api updated for sorting by testclass, status, and finished time
galasa-dev/framework pull request #250
Opened 2021-03-25 11:00 UTC by CJMeek

Signed-off-by: CJMeek <up887397@myport.ac.uk>

2021-03-25 13:07 UTC, Michael-Baylis requested changes

2021-03-25 13:07 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/RunQuery.java
> +         if(testClassSort) {
The logic of this needs to be better.   you need if, else if, else   to look at all the sort options in one go.  not as separate entities

2021-03-25 15:58 UTC, CJMeek commented
Had to add a check for the sort parameter existing otherwise they come back as true default and therefore sorting even when the parameter doesn't exist. Believe we added this to ExtractQuerySort so we didnt have to check for null every time

2021-04-06 12:26 UTC, Michael-Baylis approved these changes

2021-04-06 12:43 UTC, merged