Worklist GET request servlet
galasa-dev/framework pull request #274
Opened 2021-05-21 16:36 UTC by jadecarino

Signed-off-by: Jade Carino <jade.carino@ibm.com>

2021-05-21 17:15 UTC, jadecarino commented
Hi @Michael-Baylis please can you review the servlet code so far which is for the Worklist get/read request. I have created a WorklistItem class to hold the data and also set up a Singleton for accessing the DSS. I have tested this at the endpoint by hard coding a worklist property and value in my dss properties file. 
After line 97, if there is no run found for one of the RunIds specified in the worklist property, a JSON error is printed and no Worklist. Please can you advise whether to throw an exception instead here and print what could be found of the Worklist?

2021-05-24 12:54 UTC, Michael-Baylis requested changes
Somethings to think about

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/DynamicStatusStoreSingleton.java
> +public class DynamicStatusStoreSingleton {
I dont't think you need this.    Getting the DSS from the framework is very very quick.   so can do during each servelt call

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +			DynamicStatusStoreSingleton.setDss(dss);
dont need this at all

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +			DynamicStatusStoreSingleton.setDss(dss);
you have got the dss from the line above so you don't need to store it anywhere else.   Also singletons are BAD,  avoid if possible

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +        if(run == null) {
why?    why not return run;

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +		return worklistProperty;
why not do the json conversion in here and return an array of string runids.

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +		return worklistProperty;
doPut and DoDelete will be calling this as well

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +				id = el.toString().replaceAll("[\"]", "");
not sure what the purpose of this is.

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +				IRunResult run = null;
the following call should be in a different method.  pass the array of runids,  and return an array of worklistitem pojos

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +		 if (worklist.size() != 0) {
use isEmpty, reads better

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +			JsonObject jsonObject = new JsonParser().parse(worklistProperty).getAsJsonObject();
this bit should be done in the getWorklistPropertyFromDss method (renamed of course)

2021-05-24 12:54 UTC, Michael-Baylis commented on galasa-parent/dev.galasa.framework.api.webui/src/main/java/dev/galasa/framework/api/webui/WorklistQuery.java
> +					JsonError error = new JsonError("No run found by ID: " + id);
make sure you are using spaces in your editor instead of tabs.   the lining up is awful in this code block

2021-06-07 12:19 UTC, jadecarino commented
I am closing this PR and will open a new one once the pipeline is back up and running.

2021-06-07 12:19 UTC, closed without merging