create framework.api.common
galasa-dev/framework pull request #424
Opened 2023-06-26 08:25 UTC by techcobweb

Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

2023-06-26 08:30 UTC, galasa-team commented
Build successful

2023-06-26 16:20 UTC, techcobweb commented
@KirbyKatcher FYI ^^^

2023-06-26 16:22 UTC, galasa-team commented
Build successful

2023-06-26 16:30 UTC, galasa-team commented
Build successful

2023-06-26 16:30 UTC, galasa-team commented
Build successful

2023-06-26 16:40 UTC, galasa-team commented
Build successful

2023-06-26 17:34 UTC, galasa-team commented
Build successful

2023-06-26 17:41 UTC, galasa-team commented
Build successful

2023-06-26 21:38 UTC, galasa-team commented
Build successful

2023-06-27 16:15 UTC, galasa-team commented
Build successful

2023-07-04 15:52 UTC, KirbyKatcher requested changes

2023-07-04 15:52 UTC, KirbyKatcher commented on galasa-parent/dev.galasa.framework.api.common/src/main/java/dev/galasa/framework/api/common/Something.java
This class doesn't seem to be doing anything. Is it needed?

2023-07-04 15:52 UTC, KirbyKatcher commented on galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/rps/tree/RpsResolver.java
This is showing as missing the license comment, do we need it or is this going to be over-written by another build?

2023-07-16 16:58 UTC, galasa-team commented
Build successful

2023-07-16 16:59 UTC, galasa-team commented
Build successful

2023-07-16 17:26 UTC, galasa-team commented
Build successful

2023-07-24 16:40 UTC, galasa-team commented
Build successful

2023-07-24 16:43 UTC, galasa-team commented
Build successful

2023-07-24 16:51 UTC, eamansour approved these changes

2023-07-24 17:08 UTC, galasa-team commented
Build successful

2023-07-24 20:54 UTC, merged