Moved testclasses, resultnames and requestor endpoints to routes
galasa-dev/framework pull request #449
Opened 2023-10-02 10:24 UTC by KirbyKatcher

2023-10-02 10:32 UTC, galasa-team commented
Build successful

2023-10-02 10:35 UTC, galasa-team commented
Build successful

2023-10-02 11:00 UTC, eamansour requested changes
Looks good - can't see any tests for the testclasses route so they'd be worth adding and I've spotted a few regex patterns worth fixing

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/routes/RequestorRoute.java
> +        List<String> list = getRequestors();
Maybe rename this variable to something other than `list` (e.g. `requestors`)

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/routes/RequestorRoute.java
> +        super(responseBuilder, "\\/requestors?", framework);
This pattern will match `/ras/requestor` since we're saying the s is optional

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/routes/ResultNamesRoute.java
>  		super(responseBuilder, "\\/resultnames?", framework);
Not a change in your PR but this pattern matches `/ras/resultname` since the s is optional

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/routes/TestClassesRoute.java
> +        super(responseBuilder, "\\/testclasses?", framework);
This pattern will match `/ras/testclasse` since the s is optional

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/main/java/dev/galasa/framework/api/ras/internal/routes/TestClassesRoute.java
> +        List<RasTestClass> classArray = getTestClasses();
Could rename to `testClasses` since it's not an array

2023-10-02 11:00 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.ras/src/test/java/dev/galasa/framework/api/ras/internal/TestTestClassesRoute.java
> +}
The tests have escaped!

2023-10-02 12:44 UTC, KirbyKatcher commented on galasa-parent/dev.galasa.framework.api.ras/src/test/java/dev/galasa/framework/api/ras/internal/TestTestClassesRoute.java
> +}
Herding tests now

2023-10-02 13:25 UTC, galasa-team commented
Build successful

2023-10-02 14:20 UTC, eamansour approved these changes

2023-10-02 15:29 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-449-nqs4c for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-02 15:30 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-449-d2lmg for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-02 15:32 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-449-x2vmk for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-04 12:21 UTC, galasa-team commented
Build successful

2023-10-04 12:21 UTC, merged