Issue 1570 requestor rest changes
galasa-dev/framework pull request #452
Opened 2023-10-12 14:46 UTC by KirbyKatcher

2023-10-12 16:11 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-framework-pr-452-j6fk6 for details. If you are unable to do so, please contact a member of the Galasa team.

2023-10-13 09:47 UTC, galasa-team commented
Build successful

2023-10-13 10:45 UTC, galasa-team commented
Build successful

2023-10-13 11:09 UTC, galasa-team commented
Build successful

2023-10-13 13:14 UTC, galasa-team commented
Build successful

2023-10-13 14:35 UTC, eamansour requested changes
A few things worth changing - let me know if anything doesn't make sense!

2023-10-13 14:35 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.runs/src/main/java/dev/galasa/framework/api/runs/routes/GroupRunsRoute.java
> +        ScheduleStatus sheduleStatus = scheduleRun(scheduleRequest, groupName, requestor);
Typo "sheduleStatus"

2023-10-13 14:35 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.runs/src/test/java/dev/galasa/framework/api/runs/routes/TestGroupRunsRoute.java
> +        //String runName, String runType, String requestor, String test, String runStatus, String bundle, String testClass, String groupName
Can remove - same applies below

2023-10-13 14:53 UTC, eamansour commented on galasa-parent/dev.galasa.framework.api.authentication/src/main/java/dev/galasa/framework/api/authentication/Authorization.java
> +        if (galasaHeader != null){
Also, I think we can remove this check since it won't matter whether or not the "Galasa-Application" header exists.

2023-10-13 15:04 UTC, galasa-team commented
Build successful

2023-10-13 15:25 UTC, galasa-team commented
Build successful

2023-10-13 15:51 UTC, galasa-team commented
Build successful

2023-10-16 10:15 UTC, galasa-team commented
Build successful

2023-10-16 12:41 UTC, galasa-team commented
Build successful

2023-10-16 12:55 UTC, galasa-team commented
Build successful

2023-10-17 09:22 UTC, galasa-team commented
Build successful

2023-10-20 09:45 UTC, eamansour approved these changes

2023-10-20 15:05 UTC, galasa-team commented
Build successful

2023-10-20 15:07 UTC, galasa-team commented
Build successful

2023-10-20 15:20 UTC, merged